# Generated by Django 2.1.3 on 2018-11-27 01:43

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
