# Generated by Django 2.1.3 on 2018-11-27 02:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='partnersblurb',
        ),
        migrations.AddField(
            model_name='homepage',
            name='partnerslist',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
