# Generated by Django 2.1.3 on 2018-11-27 03:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0007_auto_20181126_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('approach', wagtail.core.fields.RichTextField(blank=True)),
                ('personnel_blurb', wagtail.core.fields.RichTextField(blank=True)),
                ('processes_blurb', wagtail.core.fields.RichTextField(blank=True)),
                ('performance_blurb', wagtail.core.fields.RichTextField(blank=True)),
                ('contract_vehicles_blurb', wagtail.core.fields.RichTextField(blank=True)),
                ('contract_vehicles_list', wagtail.core.fields.RichTextField(blank=True)),
                ('core_capabilities_list', wagtail.core.fields.RichTextField(blank=True)),
                ('test_management_pastperf', wagtail.core.fields.RichTextField(blank=True)),
                ('modeling_simulation_pastperf', wagtail.core.fields.RichTextField(blank=True)),
                ('intel_pastperf', wagtail.core.fields.RichTextField(blank=True)),
                ('cybersecurity_pastperf', wagtail.core.fields.RichTextField(blank=True)),
                ('systems_analysis_eng_pastperf', wagtail.core.fields.RichTextField(blank=True)),
                ('assistive_tech_pastperf', wagtail.core.fields.RichTextField(blank=True)),
                ('document_management_pastperf', wagtail.core.fields.RichTextField(blank=True)),
                ('distance_learning_pastperf', wagtail.core.fields.RichTextField(blank=True)),
                ('technical_admin_pastperf', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
