# Generated by Django 2.1.3 on 2018-11-27 03:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0008_servicespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('join_us_blurb', wagtail.core.fields.RichTextField(blank=True)),
                ('benefits_holidays_details', wagtail.core.fields.RichTextField(blank=True)),
                ('benefits_holidaypay_details', wagtail.core.fields.RichTextField(blank=True)),
                ('benefits_pto_details', wagtail.core.fields.RichTextField(blank=True)),
                ('benefits_health_insurance_details', wagtail.core.fields.RichTextField(blank=True)),
                ('benefits_disability_details', wagtail.core.fields.RichTextField(blank=True)),
                ('benefits_retirement_details', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('bd_contacts', wagtail.core.fields.RichTextField(blank=True)),
                ('contractvehicles_contacts', wagtail.core.fields.RichTextField(blank=True)),
                ('hr_contacts', wagtail.core.fields.RichTextField(blank=True)),
                ('general_contacts', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
